function writeMediaAccToExcel(medianTrainAccuracy, medianTestAccuracy, file)
 % Esta função escreve num ficheiro Excel os valores médios de precisão
 % (após N execuções da mesma rede com a mesma configuração).

    T2 = array2table({file, '-', '-', '-', '-', '-', '-', '-', '-', '-', ...
        medianTrainAccuracy, ...
        medianTestAccuracy}, ...
        'VariableNames', ...
        {'File', ...
        'Neurons', ...
        'TrainFunction', ...
        'InputTransferFunction', ...
        'OutputTransferFunction', ...
        'DivideFunction', ...
        'TrainRatio', ...
        'ValRatio', ...
        'TestRatio', ...
        'NumberEpochs', ...
        'TrainAccuracy', ...
        'TestAccuracy'});

    fprintf("Writing the medians:\n%.2f%% Median train acc\n%.2f%% Media test acc\n", medianTrainAccuracy, medianTestAccuracy);
    writetable(T2, 'tests.xlsx', 'WriteMode', 'append');
end