function writeNetToExcel(net, trainAccuracy, testAccuracy, file)

    % Esta função escreve os detalhes da configuração da rede treinada,
    % os seus parâmetros e os resultados de treino/teste num ficheiro Excel

    % There's more than 1 hidden layer
    % It's a deep network

    % Verifica se a rede tem mais de uma camada escondida (rede profunda)
    neurons = "";
    trainFcn = "";

    if net.numLayers > 2 
        for j = 1:net.numLayers-2
            % Concatena nº de neurónios e função de ativação por camada escondida
            neurons = neurons + net.layers{j}.dimensions + ", ";
            trainFcn = trainFcn + net.layers{j}.transferFcn + ", ";
        end   
    end  
    
    % Acrescenta a última camada oculta à descrição
    neurons = neurons + net.layers{end-1}.dimensions;
    trainFcn = trainFcn + net.layers{end-1}.transferFcn;

     % Constrói uma tabela com todos os parâmetros da rede e resultados
    T = array2table({file, ...
        neurons, ...
        net.trainFcn, ...
        trainFcn, ...
        net.layers{end}.transferFcn, ...
        net.divideFcn, ...
        net.divideParam.trainRatio, ...
        net.divideParam.valRatio, ...
        net.divideParam.testRatio, ...
        net.trainParam.epochs, ...
        trainAccuracy, ...
        testAccuracy}, ...
        'VariableNames', ...
        {'File', ...
        'Neurons', ...
        'TrainFunction', ...
        'InputTransferFunction', ...
        'OutputTransferFunction', ...
        'DivideFunction', ...
        'TrainRatio', ...
        'ValRatio', ...
        'TestRatio', ...
        'NumberEpochs', ...
        'TrainAccuracy', ...
        'TestAccuracy'});

    fprintf("Writing to excel:\n%.2f%% Global Acc\n%.2f%% Test Acc\n", trainAccuracy, testAccuracy);
    writetable(T, 'tests.xlsx', 'WriteMode','append');
end